### ISSUE TITLE
Global Variable recovery

### ISSUE THREAD

**Issue by 5angjun** [koharin/idapro_auto_decompile#1]
안녕하세요.

IDA -> C/C++로 바꿔서 다시 gcc로 컴파일할 수 있도록 하는 플러그인을 찾고 중입니다

혹시 제가 찾고 있는 기능처럼 이 플러그인을 통해서 다시 컴파일할 수 있을까요?

보니까 전역변수는 recovery가 안되는것 같아서 혹시 기능이 구현되었는지 궁금합니다.

**Comment by koharin** [comment]
안녕하세요.

바이너리를 IDA를 통해 디컴파일 하면 완전한 C/C++ 형태가 아닌 스도코드 형태입니다. 제가 제작한 도구는 IDA를 이용해서 디컴파일 코드를 생성해주는 기능까지 있기 때문에,  __fastcall, __cdecl, __int64, _BYTE 등 C/C++의 형태로 따로 포맷팅을 해야 gcc로 다시 컴파일할 수 있습니다. 
또한 제가 구현한 기능은 .text 영역의 코드만 가져와서 전역변수를 처리하려면 .data에서 가져오는 등 코드 수정이 필요할 것 같습니다. 

감사합니다.

**Comment by 5angjun** [comment]
아직은 C바로 바꾸려면 조금 수정을 해줘야되군요.

답변 감사합니다!
